Mathematical Intuition

In [23]:
#equation of hyperplane:
   # w*x+b=0
    #w=weights
    #x=input
    #b=bias/intercept
#Prediction rule:
    #if:w*x+b>=0--->class1 
    #else:w*x+b<0--->class2  
w=2
x=3
b=-4
y=w*x+b
print(y)
if y>=0:
    print("class1")
else:
    print("class2")

2
class1

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df=pd.read_csv(r"C:\Tekworks\Day 20\gender_classification_v7.csv")
df.head()

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,1,11.8,6.1,1,0,1,1,Male
1,0,14.0,5.4,0,0,1,0,Female
2,0,11.8,6.3,1,1,1,1,Male
3,0,14.4,6.1,0,1,1,1,Male
4,1,13.5,5.9,0,0,0,0,Female

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   long_hair                  5001 non-null   int64
 1   forehead_width_cm          5001 non-null   float64
 2   forehead_height_cm         5001 non-null   float64
 3   nose_wide                  5001 non-null   int64
 4   nose_long                  5001 non-null   int64
 5   lips_thin                  5001 non-null   int64
 6   distance_nose_to_lip_long  5001 non-null   int64
 7   gender                     5001 non-null   object
dtypes: float64(2), int64(5), object(1)
memory usage: 312.7+ KB

In [7]:
df.isnull().sum()

long_hair                    0
forehead_width_cm            0
forehead_height_cm           0
nose_wide                    0
nose_long                    0
lips_thin                    0
distance_nose_to_lip_long    0
gender                       0
dtype: int64

In [8]:
df.isnull()

,long_hair,forehead_width_cm,forehead_height_cm,nose_wide,nose_long,lips_thin,distance_nose_to_lip_long,gender
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
4996,False,False,False,False,False,False,False,False
4997,False,False,False,False,False,False,False,False
4998,False,False,False,False,False,False,False,False
4999,False,False,False,False,False,False,False,False
5000,False,False,False,False,False,False,False,False

In [10]:
df.dtypes.value_counts()

int64      5
float64    2
object     1
Name: count, dtype: int64

In [11]:
df.value_counts()

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  lips_thin  distance_nose_to_lip_long  gender
1          14.2               6.5                 0          0          0          0                          Female    9
           13.7               6.1                 0          0          0          0                          Female    8
           12.5               5.7                 0          0          0          0                          Female    7
           12.7               5.9                 1          1          1          1                          Male      7
           14.1               6.0                 0          0          0          0                          Female    7
                                                                                                                       ..
           12.9               5.1                 0          1          0          0                          Female    1
0          15.3               5.8                 1          1          0          1                          Male      1
                              5.3                 1          0          0          1                          Male      1
                              5.1                 1          1          0          1                          Male      1
           11.4               5.2                 0          0          0          0                          Female    1
Name: count, Length: 3233, dtype: int64

In [31]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

# Load the dataset
data = load_iris()

X = data.data
y = data.target

# Split the dataset into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create an SVM model
svm_classifier = SVC(
    kernel='rbf',     # Type of boundary
    C=1.0,            # Regularization parameter
    gamma='scale'     # Controls influence of data points
)

# Train the model
svm_classifier.fit(X_train, y_train)

# Make predictions
y_pred = svm_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00

In [ ]:
#linear = Linear data
#poly = polynomial relationship
#rbf = non linear complex data
#sigmoid = neural-network-like behavior

In [ ]:
#c=1
#controls overfitting vs underfitting
#small c ---> wider margin ---> underfit
#Large c ---> tries to classify all points ---> may overfit

In [ ]:
#gamma = scale
#controls how far the influence of one data point reaches.
#High gamma---> model memorizes the data
#Low gamma---> model is more generalized

SVC Parameters

In [38]:
svm_classifier = SVC(
    shrinking=False,  # Disable shrinking heuristics
    probability=True,  # Enable probability estimates
    degree=3,        # Degree for polynomial kernel
    break_ties=True,   # Enable tie-breaking in decision function  
    coef0=1.0         # Independent term in kernel function  
)
svm_classifier

SVC(break_ties=True, coef0=1.0, probability=True, shrinking=False)